/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AnalysisDashboard: typeof import('./components/AnalysisDashboard.vue')['default']
    ArchitectureProcess: typeof import('./components/ArchitectureProcess.vue')['default']
    BatteryCurrent: typeof import('./components/BatteryCurrent.vue')['default']
    BatteryData: typeof import('./components/BatteryData.vue')['default']
    BatteryHealth: typeof import('./components/BatteryHealth.vue')['default']
    DQDVChart: typeof import('./components/echarts/DQDVChart.vue')['default']
    DvChart: typeof import('./components/echarts/DvChart.vue')['default']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    Header: typeof import('./components/Header.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    RingPieChart: typeof import('./components/RingPieChart.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Soc: typeof import('./components/Soc.vue')['default']
    SocAnalyze: typeof import('./components/SocAnalyze.vue')['default']
    Test: typeof import('./components/echarts/test.vue')['default']
    TrainInformation: typeof import('./components/TrainInformation.vue')['default']
  }
}
